# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echobot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='NameForm',
        ),
    ]
