# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echobot', '0002_auto_20161219_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='NameForm',
        ),
    ]
